[package]
name = "growbe-mainboard"
version = "0.1.10"
edition = "2021"

[dependencies]
chrono = "0.4.0"
rumqtt = "0.31.0"
cty = "0.2.2"
env_logger = "0.9.0"
log = "0.4.14"
protobuf = "2.25.2"
uuid = "1.1.2"
futures = "0.3"
lazy_static = "1.4.0"
rusqlite = { version = "0.28.0", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.59"
tokio = { version = "1.14", features = ["full", "time", "rt-multi-thread"] }
tokio-util = "0.6.9"
tokio-stream = { version = "0.1.9", features = ["sync"] }
btleplug = { git = "https://github.com/deviceplug/btleplug", features = ["serde"] }
warp = "0.3"
nix = "0.23.0"
regex = "1.5"

[target.'cfg(target_os = "linux")'.dependencies]
rppal = "0.13.1"

[build-dependencies]
protoc-rust = "2.25.2"
