[package]
name = "growbe-mainboard"
version = "0.1.0"
edition = "2021"

[dependencies]
rumqtt = "0.31.0"
cty = "0.2.2"
protobuf = "2.25.2"
futures = "0.3"
serde_json = "1.0.59"
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }

[build-dependencies]
protoc-rust = "2.25.2"
