[package]
name = "growbe-mainboard"
version = "0.1.7"
edition = "2021"

[dependencies]
chrono = "0.4.0"
rumqtt = "0.31.0"
cty = "0.2.2"
env_logger = "0.9.0"
log = "0.4.14"
protobuf = "2.25.2"
futures = "0.3"
lazy_static = "1.4.0"
rusqlite = "0.26.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.59"
tokio = { version = "1.14", features = ["full", "time", "rt-multi-thread"] }
tokio-util = "0.6.9"
warp = "0.3"
nix = "0.23.0"
regex = "1.5"
rppal = "0.13.1"

[build-dependencies]
protoc-rust = "2.25.2"
