[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.arm-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"


[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"