name: master pipeline , developpment build

on:
  push:
    branches:
      - master

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login docker
        run: docker login https://docker.pkg.github.com -u berlingoqc -p $GITHUB_ACCESS_TOKEN
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
      - name: Download vendors
        run: ./scripts/rust_env.sh cargo vendor && ./scripts/rust_env.sh make -C ./drivers
      - name: Build x86
        run: ./scripts/rust_env.sh bash -c "COMMIT=$(git rev-parse --short "$GITHUB_SHA") cargo build --features pc --release"
      - name: Build ARMv7
        run: ./scripts/rust_env.sh make -C ./drivers clean && ./scripts/rust_env.sh make -C ./drivers CC=arm-linux-gnueabihf-gcc && COMMIT=$(git rev-parse --short "$GITHUB_SHA") ./scripts/rust_env.sh cargo build --target armv7-unknown-linux-gnueabihf --features "pi" --release
      - name: Build ARMv7 pc-module
        run: ./scripts/rust_env.sh bash -c "COMMIT=$(git rev-parse --short "$GITHUB_SHA") cargo build -p growbe-pc-module --target armv7-unknown-linux-gnueabihf --release"
      - name: Build pc-module linux
        run: ./scripts/rust_env.sh bash -c "COMMIT=$(git rev-parse --short "$GITHUB_SHA") cargo build -p growbe-pc-module --release"
      - name: Create release folder
        run: mkdir -p release && cp ./target/armv7-unknown-linux-gnueabihf/release/growbe-mainboard ./release/growbe-mainboard-arm-linux && cp ./target/armv7-unknown-linux-gnueabihf/release/growbe-mainboard ./release/growbe-pc-module-arm-linux && cp ./target/release/growbe-pc-module ./release/growbe-pc-module-x86-linux && cp ./target/release/growbe-mainboard ./release/growbe-mainboard-x86-linux
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ./release/*
      - name: Send notification to the growbe-cloud
        run: .github/notify-version.sh
        env:
          TOKEN: ${{ secrets.TOKEN }}
      - name: Notify
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed to master. ${{ github.event.head_commit.message }}'

