name: master pipeline , developpment build

on:
  push:
    branches:
      - master

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login docker
        run: docker login https://docker.pkg.github.com -u berlingoqc -p $GITHUB_ACCESS_TOKEN
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
      - name: Download vendors
        run: ./scripts/rust_env.sh cargo vendor && ./scripts/rust_env.sh make -C ./drivers
      - name: Run UT
        run: ./scripts/rust_env.sh cargo test
      - name: Build x86 for linux
        run: ./scripts/rust_env.sh cargo build
      - name: Build ARM
        run: ./scripts/rust_env.sh make -C ./drivers clean && ./scripts/rust_env.sh make -C ./drivers CC=arm-linux-gnueabihf-gcc && ./scripts/rust_env.sh cargo build --target armv7-unknown-linux-gnueabihf
      - name: Create release folder
        run: mkdir -p release && cp ./target/debug/growbe-mainboard ./release/growbe-mainboard-debug-x86_64-linux && cp ./target/armv7-unknown-linux-gnueabihf/debug/growbe-mainboard ./release/growbe-mainboard-debug-arm-linux
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ./release/*
