name: master pipeline , developpment build

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login docker
        run: docker login https://docker.pkg.github.com -u berlingoqc -p $GITHUB_ACCESS_TOKEN
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
      - name: Download vendors
        run: ./scripts/rust_env.sh cargo vendor && ./scripts/rust_env.sh make -C ./drivers
      - name: Build ARMv7
        run: ./scripts/rust_env.sh make -C ./drivers clean && ./scripts/rust_env.sh make -C ./drivers CC=arm-linux-gnueabihf-gcc && ./scripts/rust_env.sh cargo build --target armv7-unknown-linux-gnueabihf --release
      - name: Build ARMv6
        run: ./scripts/rust_env.sh cargo build --target arm-unknown-linux-gnueabihf --release
      - name: Create release folder
        run: mkdir -p release && cp ./target/armv7-unknown-linux-gnueabihf/release/growbe-mainboard ./release/growbe-mainboard-arm-linux && cp ./target/arm-unknown-linux-gnueabihf/release/growbe-mainboard ./release/growbe-mainboard-armv6-linux
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./release/*
          draft: true
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');
      - name: Send notification to the growbe-cloud
        run: docker run --env DB_URL=${{secrets.DB_URL}} MQTT_URL=${{secrets.MQTT_URL}} docker.pkg.github.com/growbe2/growbe-cloud/growbe-cloud node ./dist/growbe-version.js ${{ steps.tag.outputs.result }}
      - name: Notify
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been release ${{ github.ref }}'