name: master pipeline , developpment build

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login docker
        run: docker login https://docker.pkg.github.com -u berlingoqc -p $GITHUB_ACCESS_TOKEN
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
      - name: Download vendors
        run: ./scripts/rust_env.sh cargo vendor && ./scripts/rust_env.sh make -C ./drivers
      - name: Build ARMv7
        run: ./scripts/rust_env.sh make -C ./drivers clean && ./scripts/rust_env.sh make -C ./drivers CC=arm-linux-gnueabihf-gcc && ./scripts/rust_env.sh cargo build --target armv7-unknown-linux-gnueabihf --release
      - name: Create release folder
        run: mkdir -p release && cp ./target/armv7-unknown-linux-gnueabihf/release/growbe-mainboard ./release/growbe-mainboard-arm-linux
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./release/*
          draft: true
      - name: Get the version
        id: tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Send notification to the growbe-cloud
        run: docker run --env API_URL=http://api.growbe.ca --env SSO_URL=https://auth.growbe.ca --env PASSWORD=${{secrets.PASSWORD}} --env EMAIL=${{secrets.EMAIL}} docker.pkg.github.com/growbe2/growbe-cloud/growbe-cloud:1.2.5-SNAPSHOT-060422-03h-c5cba69 node ./dist/growbe-version.js ${{ steps.tag.outputs.result  }}
      - name: Notify
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been release ${{ github.ref }}'
